version: "3"
networks:
  api_server_default:
    external: false
services:
  prolife-admin:
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    ports:
      - 80:5001
